/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Item, User, Booking, PresetItem } from './types';

export const CATEGORIES = [
  { id: 'all', name: 'All Categories', count: 12 },
  { id: 'textbooks', name: 'Textbooks & Academics', count: 3 },
  { id: 'electronics', name: 'Electronics & Tech', count: 3 },
  { id: 'transport', name: 'Bikes & Electric Scooters', count: 2 },
  { id: 'appliances', name: 'Dorm Kitchen & Appliances', count: 2 },
  { id: 'sports', name: 'Sports & Outdoors', count: 2 },
];

export const MOCK_USERS: User[] = [
  {
    id: 'user_alex',
    name: 'Alex Rivera',
    email: 'alex.rivera@university.edu',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=120',
    balance: 145.0,
    reputation: 4.9,
  },
  {
    id: 'user_emma',
    name: 'Emma Watson',
    email: 'emma.w@university.edu',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=120',
    balance: 82.5,
    reputation: 4.8,
  },
  {
    id: 'user_sam',
    name: 'Sam Chen',
    email: 'sam.c@university.edu',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=120',
    balance: 210.0,
    reputation: 5.0,
  },
  {
    id: 'user_lily',
    name: 'Lily Green',
    email: 'lily.g@university.edu',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=120',
    balance: 50.0,
    reputation: 4.7,
  }
];

export const INITIAL_ITEMS: Item[] = [
  {
    id: 'item_1',
    title: 'TI-84 Plus CE Graphing Calculator',
    description: 'Perfect for Calculus and Statistics. Colored backlit screen. Battery is fully charged and comes with the charging cable. I only need it for exams, so feel free to rent it for your midterm weeks!',
    category: 'textbooks',
    ownerId: 'user_emma',
    ownerName: 'Emma Watson',
    ownerAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=120',
    type: 'borrow',
    price: 3.5, // $3.50 per day
    condition: 'Like New',
    imageUrl: 'https://images.unsplash.com/photo-1629130764083-ec55d4a1a942?auto=format&fit=crop&q=80&w=600',
    available: true,
    location: 'West Quad Dorms',
    rating: 4.9,
    reviewsCount: 12,
  },
  {
    id: 'item_2',
    title: 'Segway Ninebot Max Electric Scooter',
    description: 'Speeds up to 18.6 mph, excellent range. Great for quickly getting across campus from North Drifts to South Quad. Please wear a helmet! Charger included inside the carry-case.',
    category: 'transport',
    ownerId: 'user_sam',
    ownerName: 'Sam Chen',
    ownerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=120',
    type: 'borrow',
    price: 12.0, // $12.00 per day
    condition: 'Good',
    imageUrl: 'https://images.unsplash.com/photo-1608613426749-ce12b98f2441?auto=format&fit=crop&q=80&w=600',
    available: true,
    location: 'Main Library Annex',
    rating: 4.8,
    reviewsCount: 24,
  },
  {
    id: 'item_3',
    title: 'Instant Pot Duo 7-in-1 Multi-Cooker',
    description: '6-Quart capacity, great for cooking easy rice, soups, and slow meals in your dorm kitchen space. Cleaned, sanitized, and ready for your weekend meal prep.',
    category: 'appliances',
    ownerId: 'user_lily',
    ownerName: 'Lily Green',
    ownerAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=120',
    type: 'borrow',
    price: 5.0, // $5.00 per day
    condition: 'Like New',
    imageUrl: 'https://images.unsplash.com/photo-1585238202521-fc5ebf600490?auto=format&fit=crop&q=80&w=600',
    available: true,
    location: 'Heritage Hall, Rm 304',
    rating: 5.0,
    reviewsCount: 8,
  },
  {
    id: 'item_4',
    title: 'Organic Chemistry (Wade, 9th Edition)',
    description: 'Essential textbook for CHEM 230. Barely highlighted, very clean pages. Comes with the molecular model kit which saves you a lot of headache on modern molecular configurations!',
    category: 'textbooks',
    ownerId: 'user_sam',
    ownerName: 'Sam Chen',
    ownerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=120',
    type: 'buy',
    price: 45.0, // Sell price
    condition: 'Good',
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=600',
    available: true,
    location: 'Science Center Lounge',
    rating: 4.7,
    reviewsCount: 5,
  },
  {
    id: 'item_5',
    title: 'Sony WH-1000XM4 Noise Cancelling Headphones',
    description: 'Perfect for intensive studying in crowded library halls. Best-in-class noise cancellation, superb battery life. Cleaned with isopropyl alcohol before handoff.',
    category: 'electronics',
    ownerId: 'user_emma',
    ownerName: 'Emma Watson',
    ownerAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=120',
    type: 'borrow',
    price: 8.0, // per day
    condition: 'Like New',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=600',
    available: true,
    location: 'West Quad Dorms',
    rating: 4.9,
    reviewsCount: 19,
  },
  {
    id: 'item_6',
    title: '2-Person Dome Camping Tent',
    description: 'Waterproof rainfly, lightweight poles, super easy 10-minute setup. Perfect for the Outdoor Club weekend trips! Includes a free tarp for ground protection.',
    category: 'sports',
    ownerId: 'user_alex',
    ownerName: 'Alex Rivera',
    ownerAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=120',
    type: 'borrow',
    price: 9.5, // per day
    condition: 'Good',
    imageUrl: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&q=80&w=600',
    available: true,
    location: 'Graduate Housing Apt C',
    rating: 4.6,
    reviewsCount: 7,
  },
  {
    id: 'item_7',
    title: 'Canon EOS Rebel T7 DSLR Camera',
    description: 'Comes with 18-55mm lens, battery charger, and 64GB high speed SD card. Perfect for photographing graduation sessions, sports matches, or school club projects!',
    category: 'electronics',
    ownerId: 'user_lily',
    ownerName: 'Lily Green',
    ownerAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=120',
    type: 'borrow',
    price: 15.0, // per day
    condition: 'Like New',
    imageUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80&w=600',
    available: true,
    location: 'Heritage Hall, Rm 304',
    rating: 4.9,
    reviewsCount: 15,
  },
  {
    id: 'item_8',
    title: 'Spikeball Standard 3-Ball Set',
    description: 'Ultimate lawn/quad game. Comes with standard net, 3 balls, ball pump, and a handy carry bag. Ideal for quad gathering or beach hangouts.',
    category: 'sports',
    ownerId: 'user_emma',
    ownerName: 'Emma Watson',
    ownerAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=120',
    type: 'borrow',
    price: 4.0, // per day
    condition: 'Good',
    imageUrl: 'https://images.unsplash.com/photo-1628155930542-3c7a64e2c833?auto=format&fit=crop&q=80&w=600',
    available: true,
    location: 'West Quad Dorms',
    rating: 4.8,
    reviewsCount: 11,
  },
  {
    id: 'item_9',
    title: 'Anker Nebula Cosmos 1080p Projector',
    description: 'Incredible brightness and audio. Set up a massive outdoor movie night in the quad, or project on your blank dorm wall. Built in Android TV with Netflix/Prime.',
    category: 'electronics',
    ownerId: 'user_alex',
    ownerName: 'Alex Rivera',
    ownerAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=120',
    type: 'borrow',
    price: 18.0, // per day
    condition: 'Like New',
    imageUrl: 'https://images.unsplash.com/photo-1535016120720-40c646be5580?auto=format&fit=crop&q=80&w=600',
    available: true,
    location: 'Graduate Housing Apt C',
    rating: 5.0,
    reviewsCount: 14,
  }
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'booking_1',
    itemId: 'item_1',
    itemTitle: 'TI-84 Plus CE Graphing Calculator',
    itemType: 'borrow',
    itemPrice: 3.5,
    imageUrl: 'https://images.unsplash.com/photo-1629130764083-ec55d4a1a942?auto=format&fit=crop&q=80&w=600',
    ownerId: 'user_emma',
    ownerName: 'Emma Watson',
    borrowerId: 'user_alex',
    borrowerName: 'Alex Rivera',
    startDate: '2026-06-12',
    endDate: '2026-06-15',
    totalCost: 10.5,
    status: 'active',
    paymentStatus: 'held_in_escrow',
    createdAt: '2026-06-10T14:30:00Z',
  },
  {
    id: 'booking_2',
    itemId: 'item_3',
    itemTitle: 'Instant Pot Duo 7-in-1 Multi-Cooker',
    itemType: 'borrow',
    itemPrice: 5.0,
    imageUrl: 'https://images.unsplash.com/photo-1585238202521-fc5ebf600490?auto=format&fit=crop&q=80&w=600',
    ownerId: 'user_lily',
    ownerName: 'Lily Green',
    borrowerId: 'user_alex',
    borrowerName: 'Alex Rivera',
    startDate: '2026-06-08',
    endDate: '2026-06-10',
    totalCost: 10.0,
    status: 'completed',
    paymentStatus: 'released',
    createdAt: '2026-06-07T09:15:00Z',
  }
];

export const PRESET_ITEMS_FOR_LISTING: PresetItem[] = [
  {
    title: 'University Calculus Study Guide (Thomas)',
    category: 'textbooks',
    description: 'Covers single & multivariable systems. Practice exams included inside. Clean margins.',
    price: 15.0,
    type: 'buy',
    imageUrl: 'https://images.unsplash.com/photo-1588580000645-4562a6d2c839?auto=format&fit=crop&q=80&w=400',
    condition: 'Good',
  },
  {
    title: 'Air Fryer XL (Ninja 5.5-Qt)',
    category: 'appliances',
    description: 'Extremely fast cooking, fits on typical dorm desks easily. Fully hand-washed and ready.',
    price: 6.0,
    type: 'borrow',
    imageUrl: 'https://images.unsplash.com/photo-1621972750749-0fbb1abb7736?auto=format&fit=crop&q=80&w=400',
    condition: 'Like New',
  },
  {
    title: 'Acoustic Guitar with Travel Case',
    category: 'sports',
    description: 'Perfect for campus quad jams or practicing in dorm rooms. Tuner and selection of picks included.',
    price: 8.0,
    type: 'borrow',
    imageUrl: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&q=80&w=400',
    condition: 'Good',
  }
];
